//! INSTANCIANDO CLASS SEM ATRUBUTOS
// ORIENTAÇÃO A OBJETO
// MÉTODO TRADICIONAL
// SINTAX
// IMPORTANTE INICIAR COM LETRA MAIUSCULA
class NomeClasse{
    // MÉTODO CONSTRUTOR
    constructor(){
        this.nome="jota"
    }
}
// PARA INSTANCIAR A CLSSE TEMOS QUE CHAMAR O FUNÇÃO NEW E O NOME DA CLASSE 
// NEW INSTANCIA A NOVA CLASSE E CHAMA O MÉRODO CONSTRUTOR
let novoObjetos = new NomeClasse()

// APÓS INSTANCIAR PODEMOS MANIPULAR
console.log(novoObjetos.nome)
console.log(novoObjetos)